[package]
name = "spot-finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-nats = "0.27.1"
futures-util = "0.3.26"
osmpbfreader = "0.16.0"
tokio = "1.25.0"
