name: Build and Test

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - latest
      - develop

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - run: |
          cargo build
          cargo test
